#!/bin/bash
# Streamlick TURN Server Deployment Script (Ubuntu + systemd)

set -e

echo "=== Streamlick TURN Server Setup (Ubuntu) ==="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (sudo ./deploy.sh)"
    exit 1
fi

# Check Ubuntu
if ! grep -q "Ubuntu" /etc/os-release; then
    echo "WARNING: This script is designed for Ubuntu. It may work on other Debian-based systems."
fi

# Install coturn
echo "Installing coturn..."
apt-get update
apt-get install -y coturn

# Create .env if not exists
if [ ! -f .env ]; then
    echo "Creating .env from .env.example..."
    cp .env.example .env

    # Try to auto-detect external IP
    EXTERNAL_IP=$(curl -s ifconfig.me || curl -s icanhazip.com || echo "")
    if [ -n "$EXTERNAL_IP" ]; then
        echo "Detected external IP: $EXTERNAL_IP"
        sed -i "s/^EXTERNAL_IP=.*/EXTERNAL_IP=$EXTERNAL_IP/" .env
    else
        echo "WARNING: Could not detect external IP. Please set EXTERNAL_IP in .env"
    fi

    # Generate random password
    RANDOM_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
    sed -i "s/^TURN_PASSWORD=.*/TURN_PASSWORD=$RANDOM_PASS/" .env

    echo ""
    echo "Generated credentials:"
    echo "  Username: streamlick"
    echo "  Password: $RANDOM_PASS"
    echo ""
    echo "IMPORTANT: Edit .env to customize settings before continuing"
    echo "Press Enter to continue or Ctrl+C to edit .env first..."
    read
fi

# Load environment variables
source .env

# Validate required settings
if [ -z "$EXTERNAL_IP" ]; then
    echo "ERROR: EXTERNAL_IP is not set in .env"
    exit 1
fi

# Configure firewall
echo "Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 3478/tcp comment "TURN TCP"
    ufw allow 3478/udp comment "TURN UDP"
    ufw allow 5349/tcp comment "TURN TLS"
    ufw allow 5349/udp comment "TURN DTLS"
    ufw allow 49152:65535/udp comment "TURN relay ports"
    echo "UFW rules added"
else
    echo "WARNING: UFW not found. Please manually open ports:"
    echo "  TCP: 3478, 5349"
    echo "  UDP: 3478, 5349, 49152-65535"
fi

# Create coturn config
echo "Creating coturn configuration..."
cat > /etc/turnserver.conf << EOF
# Coturn TURN Server Configuration for Streamlick
# Generated by deploy.sh

# Network settings
listening-port=3478
tls-listening-port=5349

# External IP (your server's public IP)
external-ip=$EXTERNAL_IP

# Relay port range (must be open in firewall)
min-port=49152
max-port=65535

# Authentication
realm=${TURN_REALM:-turn.streamlick.com}
user=${TURN_USERNAME:-streamlick}:${TURN_PASSWORD:-changeme}

# Enable long-term credentials mechanism
lt-cred-mech

# TLS certificates (uncomment and set paths for TURNS)
EOF

# Add TLS config if certificates are specified
if [ -n "$TURN_TLS_CERT" ] && [ -n "$TURN_TLS_KEY" ]; then
    echo "cert=$TURN_TLS_CERT" >> /etc/turnserver.conf
    echo "pkey=$TURN_TLS_KEY" >> /etc/turnserver.conf
fi

cat >> /etc/turnserver.conf << EOF

# Logging
log-file=/var/log/turnserver/turnserver.log
verbose

# Security settings
fingerprint
no-software-attribute

# Disable multicast peers (security)
no-multicast-peers

# Don't let peers connect to private IPs (security)
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=127.0.0.0-127.255.255.255

# Allow localhost for testing
allowed-peer-ip=127.0.0.1

# Enable mobility (for mobile networks)
mobility

# Use both STUN and TURN
stun-only=false
EOF

# Create log directory
mkdir -p /var/log/turnserver
chown turnserver:turnserver /var/log/turnserver

# Enable coturn in default config
echo "Enabling coturn service..."
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

# Restart coturn
echo "Starting coturn service..."
systemctl enable coturn
systemctl restart coturn

# Wait for startup
sleep 2

# Check status
if systemctl is-active --quiet coturn; then
    echo ""
    echo "=== TURN Server Started Successfully! ==="
    echo ""
    echo "Server URL: turn://$EXTERNAL_IP:3478"
    echo "TLS URL:    turns://$EXTERNAL_IP:5349 (requires SSL certs)"
    echo ""
    echo "Add to your Streamlick frontend .env:"
    echo "  VITE_TURN_SERVER_URL=turn://$EXTERNAL_IP:3478"
    echo "  VITE_TURN_SERVER_USERNAME=${TURN_USERNAME:-streamlick}"
    echo "  VITE_TURN_SERVER_CREDENTIAL=${TURN_PASSWORD}"
    echo ""
    echo "Test your server at:"
    echo "  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/"
    echo ""
    echo "Monitor logs with:"
    echo "  sudo tail -f /var/log/turnserver/turnserver.log"
    echo "  sudo journalctl -u coturn -f"
    echo ""
    echo "Manage service with:"
    echo "  sudo systemctl status coturn"
    echo "  sudo systemctl restart coturn"
else
    echo "ERROR: TURN server failed to start"
    systemctl status coturn
    exit 1
fi
